/**
 * Bridges research.json → ToyTools content. Reads a tool's research brief and
 * emits agent-ready stubs under output/<slug>/ — it never touches src/. The
 * engine supplies *what to cover* (deterministic); a coding agent (or you)
 * writes the prose using the generated PROMPT.md.
 *
 *   tsx scripts/scaffold.ts <tool-slug>
 *
 * Produces:
 *   output/<slug>/faq.draft.ts       — FAQItem[] seeded with real questions, TODO answers
 *   output/<slug>/knowledge.draft.ts — Knowledge stub (concepts/intents pre-filled, relations TODO)
 *   output/<slug>/guide.outline.md   — section outline (table-stakes vs. gaps)
 *   output/<slug>/PROMPT.md          — a ready-to-paste prompt for Claude Code
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { titleCase, normalizeHeading } from './utils/text.js';
import type { ResearchDocument } from '../types/index.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

const toolSlug = process.argv[2];
if (!toolSlug) {
  console.error('Usage: tsx scripts/scaffold.ts <tool-slug>');
  process.exit(1);
}

const researchPath = join(ROOT, 'research', 'processed', toolSlug, 'research.json');
if (!existsSync(researchPath)) {
  console.error(`No research.json for "${toolSlug}". Run seo:extract first.`);
  process.exit(1);
}

const doc = JSON.parse(readFileSync(researchPath, 'utf-8')) as ResearchDocument;
const name = titleCase(toolSlug.replace(/-/g, ' '));
const abbr = toolSlug.split('-').map(t => t[0]).join('').slice(0, 3) || 'tt';

// Question pool, deduped. Lead with questions that mention a slug token (the
// on-topic ones) so the draft surfaces relevant questions first and pushes
// competitor-specific noise ("What is Webhook?") below the cap.
const slugTokens = toolSlug.split('-').filter(t => t.length > 2);
const isOnTopic = (q: string) => slugTokens.some(tok => q.toLowerCase().includes(tok));

// Strip enumerator prefixes ("Q.", "1.") for display; dedupe on a normalized
// key so "What is the Pomodoro Technique?" and "Q. What is Pomodoro Technique?"
// collapse to one entry.
const cleanQuestion = (q: string) => q.replace(/^\s*(q[\.\):]|\d+[\.\)\:])\s*/i, '').trim();

// Reddit question + misconception clusters represent *real, high-demand* user
// questions — fold them into the FAQ pool (highest-engagement first) so authored
// FAQs answer what users actually ask, not just what competitors happen to cover.
const redditQuestions = (doc.redditQuestions ?? []).map(s => s.topic);
const redditMisconceptions = (doc.redditMisconceptions ?? []).map(s => s.topic);
const pool = [...redditQuestions, ...redditMisconceptions, ...doc.questions, ...doc.competitorFaqs]
  .map(q => q.trim())
  .filter(Boolean);
const seen = new Set<string>();
const questions: string[] = [];
for (const raw of [...pool.filter(isOnTopic), ...pool.filter(q => !isOnTopic(q))]) {
  const key = normalizeHeading(raw).replace(/\?+$/, '');
  if (!key || seen.has(key)) continue;
  seen.add(key);
  questions.push(cleanQuestion(raw));
  if (questions.length >= 12) break;
}

const outDir = join(ROOT, 'output', toolSlug);
mkdirSync(outDir, { recursive: true });

// ---- faq.draft.ts ----------------------------------------------------------
const faqItems = questions
  .map((q, i) => {
    const question = q.endsWith('?') ? q : `${q}?`;
    return `  {\n    id: '${abbr}-faq-${i + 1}',\n    question: ${JSON.stringify(question)},\n    answer: 'TODO: answer from the research brief.',\n  },`;
  })
  .join('\n');

const faqDraft = `import type { FAQItem } from '@data/types';

// DRAFT generated by \`seo:scaffold ${toolSlug}\` from research.json.
// Fill in each answer, prune off-topic questions, then move into
// src/tools/${toolSlug}/faq.ts and wire it per CLAUDE.md.
export const items: FAQItem[] = [
${faqItems}
];
`;
writeFileSync(join(outDir, 'faq.draft.ts'), faqDraft);

// ---- guide.outline.md ------------------------------------------------------
const bullets = (arr: string[], empty: string) =>
  arr.length ? arr.map(s => `- ${s}`).join('\n') : `_${empty}_`;

// User-demand block, sourced from Reddit intent signals. These are *topics to
// address in original prose* — never Reddit text to reproduce.
const opportunities = (doc.contentOpportunities ?? []).map(o => `${o.topic} _(opportunity ${o.score})_`);
const comparisons = (doc.redditComparisons ?? []).map(s => s.topic);
const painPoints = (doc.redditPainPoints ?? []).map(s => s.topic);
const misconceptions = (doc.redditMisconceptions ?? []).map(s => s.topic);
const hasReddit = (doc.sampleSize ?? 0) > 0;

const userDemandSection = hasReddit
  ? `
## User demand (from Reddit intent — address as original prose, do NOT reproduce Reddit text)

> Demand ${doc.redditDemandScore}/100 · confidence ${doc.dataConfidence} (n=${doc.sampleSize})${doc.audienceTypes?.length ? ` · audience: ${doc.audienceTypes.join(', ')}` : ''}

**Ranked content opportunities**
${bullets(opportunities, 'None detected.')}

**Comparisons users make**
${bullets(comparisons, 'None detected.')}

**Pain points to troubleshoot**
${bullets(painPoints, 'None detected.')}

**Misconceptions to correct (strong GEO/FAQ opportunities)**
${bullets(misconceptions, 'None detected.')}
`
  : '';

const guideOutline = `# ${name} — Guide outline

> Generated by \`seo:scaffold ${toolSlug}\`. Section ordering is a starting point.

**Primary intent:** ${doc.primaryIntent} · **Secondary intent:** ${doc.secondaryIntent}

**Entities to mention:** ${doc.entities.slice(0, 12).join(', ') || '—'}

## Table-stakes sections (competitor consensus)
${bullets(doc.competitorHeadings, 'No cross-site consensus formed — see related topics and gaps below.')}

## Differentiation — gaps competitors miss (lead with these)
${bullets(doc.contentGaps.slice(0, 12), 'None detected.')}
${userDemandSection}
## Related topics
${bullets(doc.relatedTopics, 'None detected.')}
`;
writeFileSync(join(outDir, 'guide.outline.md'), guideOutline);

// ---- knowledge.draft.ts ----------------------------------------------------
// Seeds the Phase D knowledge layer from research. Relationship fields (usedWith/
// alternatives/nextSteps) need human judgement about sibling tools, so they're left
// as TODO stubs with the RelationshipReference shape; everything else is pre-filled.
const useCases = (doc.redditUseCases ?? []).map(s => s.topic);
const terminology = (doc.redditTerminology ?? []).map(s => s.topic);
const jsArr = (arr: string[], n = 6) =>
  arr.slice(0, n).map(s => JSON.stringify(s)).join(', ');

const knowledgeDraft = `import { KNOWLEDGE_SCHEMA_VERSION, type Knowledge } from '@lib/knowledge/types';

// DRAFT generated by \`seo:scaffold ${toolSlug}\` from research.json.
// Fill the relationship fields (usedWith / alternatives / nextSteps) with real sibling
// tool slugs + a human \`reason\`, set workflowStage, then move to
// src/tools/<segment>/${toolSlug}/knowledge.ts and add it to src/lib/knowledge/registry.ts.
export const knowledge: Knowledge = {
  schemaVersion: KNOWLEDGE_SCHEMA_VERSION,
  slug: ${JSON.stringify(toolSlug)},
  title: ${JSON.stringify(name)},
  category: 'developer-tools', // TODO: set the tool's categorySlug
  summary: 'TODO: one-line summary, max 160 chars.',
  primaryConcepts: [${jsArr(doc.entities, 2)}],
  secondaryConcepts: [${jsArr(doc.entities.slice(2), 5)}],
  intentGroups: {
    informational: [${jsArr(doc.questions, 4)}],
    howTo: [],
    comparison: [${jsArr(comparisons, 3)}],
    misconception: [${jsArr(misconceptions, 3)}],
    troubleshooting: [${jsArr(painPoints, 3)}],
  },
  realWorldUseCases: [${jsArr(useCases, 4)}],
  commonMistakes: [], // TODO from misconceptions / pain points
  commonQuestions: [${jsArr(questions, 3)}],
  usedWith: [], // TODO: [{ slug: 'sibling-tool', reason: 'why', strength: 0.8 }]
  alternatives: [], // TODO: [{ slug: 'alt-tool', reason: 'when to choose it' }]
  nextSteps: [], // TODO: [{ slug: 'next-tool', reason: 'what to do next', priority: 1 }]
  workflowStage: ['transform'], // TODO: input | transform | validate | analyze | export
  keywords: [${jsArr(doc.entities, 6)}],
  entityAliases: [${jsArr(terminology, 4)}],
};
`;
writeFileSync(join(outDir, 'knowledge.draft.ts'), knowledgeDraft);

// ---- PROMPT.md -------------------------------------------------------------
const prompt = `# Agent prompt — generate ${name} content

Read \`seo-engine/research/processed/${toolSlug}/research.json\` and follow the
tool-authoring pattern in CLAUDE.md. Keep everything grayscale, minimal-JS,
mobile-first, and route internal links through \`withBase\`.

1. Write \`src/tools/${toolSlug}/faq.ts\` (FAQItem[]) answering the questions in
   \`output/${toolSlug}/faq.draft.ts\`. Drop any that are off-topic for this tool;
   answer the rest accurately and concisely.
2. Write/extend \`Guide.astro\` using \`output/${toolSlug}/guide.outline.md\`:
   cover the table-stakes sections, but **lead with the differentiation gaps** —
   that is where this page can outrank competitors.
3. Add the \`faq\`/\`guide\` config to \`config.ts\` and register per CLAUDE.md.
4. Write \`src/tools/${toolSlug}/knowledge.ts\` from \`output/${toolSlug}/knowledge.draft.ts\`:
   fill the relationship fields (usedWith / alternatives / nextSteps) with real sibling tool
   slugs and a human \`reason\`, set \`workflowStage\`, and register it in
   \`src/lib/knowledge/registry.ts\`. Derived related tools/guides/FAQs are automatic — only
   the curated overlay fields need authoring.

Mention these entities where natural: ${doc.entities.slice(0, 10).join(', ')}.
${hasReddit ? `
## User demand (Reddit intent)

The "User demand" section of \`guide.outline.md\` lists what real users ask,
compare, and misunderstand (demand ${doc.redditDemandScore}/100, n=${doc.sampleSize}). Prioritise
covering the ranked opportunities and **answer the misconceptions explicitly** —
these are exactly the Q&A blocks answer engines (GEO) surface.

**Hard rule:** these are research signals for *what to cover*. Write everything
in your own original prose. Never copy, paraphrase, or rephrase Reddit titles,
posts, or comments into the published content.
` : ''}`;
writeFileSync(join(outDir, 'PROMPT.md'), prompt);

console.log(`\n=== Scaffolded ${toolSlug} ===`);
console.log(`  ${questions.length} questions → output/${toolSlug}/faq.draft.ts`);
console.log(`  Knowledge stub   → output/${toolSlug}/knowledge.draft.ts`);
console.log(`  Guide outline    → output/${toolSlug}/guide.outline.md`);
console.log(`  Agent prompt     → output/${toolSlug}/PROMPT.md`);
console.log(`\nHand PROMPT.md to Claude Code, or fill the drafts yourself.\n`);
