/**
 * Bridges research.json → ToyTools content. Reads a tool's research brief and
 * emits agent-ready stubs under output/<slug>/ — it never touches src/. The
 * engine supplies *what to cover* (deterministic); a coding agent (or you)
 * writes the prose using the generated PROMPT.md.
 *
 *   tsx scripts/scaffold.ts <tool-slug>
 *
 * Produces:
 *   output/<slug>/faq.draft.ts     — FAQItem[] seeded with real questions, TODO answers
 *   output/<slug>/guide.outline.md — section outline (table-stakes vs. gaps)
 *   output/<slug>/PROMPT.md        — a ready-to-paste prompt for Claude Code
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { titleCase, normalizeHeading } from './utils/text.js';
import type { ResearchDocument } from '../types/index.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

const toolSlug = process.argv[2];
if (!toolSlug) {
  console.error('Usage: tsx scripts/scaffold.ts <tool-slug>');
  process.exit(1);
}

const researchPath = join(ROOT, 'research', 'processed', toolSlug, 'research.json');
if (!existsSync(researchPath)) {
  console.error(`No research.json for "${toolSlug}". Run seo:extract first.`);
  process.exit(1);
}

const doc = JSON.parse(readFileSync(researchPath, 'utf-8')) as ResearchDocument;
const name = titleCase(toolSlug.replace(/-/g, ' '));
const abbr = toolSlug.split('-').map(t => t[0]).join('').slice(0, 3) || 'tt';

// Question pool, deduped. Lead with questions that mention a slug token (the
// on-topic ones) so the draft surfaces relevant questions first and pushes
// competitor-specific noise ("What is Webhook?") below the cap.
const slugTokens = toolSlug.split('-').filter(t => t.length > 2);
const isOnTopic = (q: string) => slugTokens.some(tok => q.toLowerCase().includes(tok));

// Strip enumerator prefixes ("Q.", "1.") for display; dedupe on a normalized
// key so "What is the Pomodoro Technique?" and "Q. What is Pomodoro Technique?"
// collapse to one entry.
const cleanQuestion = (q: string) => q.replace(/^\s*(q[\.\):]|\d+[\.\)\:])\s*/i, '').trim();

const pool = [...doc.questions, ...doc.competitorFaqs].map(q => q.trim()).filter(Boolean);
const seen = new Set<string>();
const questions: string[] = [];
for (const raw of [...pool.filter(isOnTopic), ...pool.filter(q => !isOnTopic(q))]) {
  const key = normalizeHeading(raw).replace(/\?+$/, '');
  if (!key || seen.has(key)) continue;
  seen.add(key);
  questions.push(cleanQuestion(raw));
  if (questions.length >= 12) break;
}

const outDir = join(ROOT, 'output', toolSlug);
mkdirSync(outDir, { recursive: true });

// ---- faq.draft.ts ----------------------------------------------------------
const faqItems = questions
  .map((q, i) => {
    const question = q.endsWith('?') ? q : `${q}?`;
    return `  {\n    id: '${abbr}-faq-${i + 1}',\n    question: ${JSON.stringify(question)},\n    answer: 'TODO: answer from the research brief.',\n  },`;
  })
  .join('\n');

const faqDraft = `import type { FAQItem } from '@data/types';

// DRAFT generated by \`seo:scaffold ${toolSlug}\` from research.json.
// Fill in each answer, prune off-topic questions, then move into
// src/tools/${toolSlug}/faq.ts and wire it per CLAUDE.md.
export const items: FAQItem[] = [
${faqItems}
];
`;
writeFileSync(join(outDir, 'faq.draft.ts'), faqDraft);

// ---- guide.outline.md ------------------------------------------------------
const bullets = (arr: string[], empty: string) =>
  arr.length ? arr.map(s => `- ${s}`).join('\n') : `_${empty}_`;

const guideOutline = `# ${name} — Guide outline

> Generated by \`seo:scaffold ${toolSlug}\`. Section ordering is a starting point.

**Primary intent:** ${doc.primaryIntent} · **Secondary intent:** ${doc.secondaryIntent}

**Entities to mention:** ${doc.entities.slice(0, 12).join(', ') || '—'}

## Table-stakes sections (competitor consensus)
${bullets(doc.competitorHeadings, 'No cross-site consensus formed — see related topics and gaps below.')}

## Differentiation — gaps competitors miss (lead with these)
${bullets(doc.contentGaps.slice(0, 12), 'None detected.')}

## Related topics
${bullets(doc.relatedTopics, 'None detected.')}
`;
writeFileSync(join(outDir, 'guide.outline.md'), guideOutline);

// ---- PROMPT.md -------------------------------------------------------------
const prompt = `# Agent prompt — generate ${name} content

Read \`seo-engine/research/processed/${toolSlug}/research.json\` and follow the
tool-authoring pattern in CLAUDE.md. Keep everything grayscale, minimal-JS,
mobile-first, and route internal links through \`withBase\`.

1. Write \`src/tools/${toolSlug}/faq.ts\` (FAQItem[]) answering the questions in
   \`output/${toolSlug}/faq.draft.ts\`. Drop any that are off-topic for this tool;
   answer the rest accurately and concisely.
2. Write/extend \`Guide.astro\` using \`output/${toolSlug}/guide.outline.md\`:
   cover the table-stakes sections, but **lead with the differentiation gaps** —
   that is where this page can outrank competitors.
3. Add the \`faq\`/\`guide\` config to \`config.ts\` and register per CLAUDE.md.

Mention these entities where natural: ${doc.entities.slice(0, 10).join(', ')}.
`;
writeFileSync(join(outDir, 'PROMPT.md'), prompt);

console.log(`\n=== Scaffolded ${toolSlug} ===`);
console.log(`  ${questions.length} questions → output/${toolSlug}/faq.draft.ts`);
console.log(`  Guide outline    → output/${toolSlug}/guide.outline.md`);
console.log(`  Agent prompt     → output/${toolSlug}/PROMPT.md`);
console.log(`\nHand PROMPT.md to Claude Code, or fill the drafts yourself.\n`);
