/**
 * Bridges research.json → ToyTools content. Reads a tool's research brief and
 * emits agent-ready stubs under output/<slug>/ — it never touches src/. The
 * engine supplies *what to cover* (deterministic); a coding agent (or you)
 * writes the prose using the generated PROMPT.md.
 *
 *   tsx scripts/scaffold.ts <tool-slug>
 *
 * Produces:
 *   output/<slug>/faq.draft.ts       — FAQItem[] seeded with real questions, TODO answers
 *   output/<slug>/knowledge.draft.ts — Knowledge stub (concepts/intents pre-filled, relations TODO)
 *   output/<slug>/guide.outline.md   — section outline (table-stakes vs. gaps)
 *   output/<slug>/PROMPT.md          — a ready-to-paste prompt for Claude Code
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { titleCase, normalizeHeading } from './utils/text.js';
import { isSpecificEntity } from './utils/terms.js';
import { getGraphTool } from './utils/tool-profile.js';
import type { ResearchDocument } from '../types/index.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const PROJECT = join(ROOT, '..');

const toolSlug = process.argv[2];
if (!toolSlug) {
  console.error('Usage: tsx scripts/scaffold.ts <tool-slug>');
  process.exit(1);
}

const researchPath = join(ROOT, 'research', 'processed', toolSlug, 'research.json');
if (!existsSync(researchPath)) {
  console.error(`No research.json for "${toolSlug}". Run seo:extract first.`);
  process.exit(1);
}

const doc = JSON.parse(readFileSync(researchPath, 'utf-8')) as ResearchDocument;
const graphTool = getGraphTool(toolSlug);
const name = graphTool?.name ?? titleCase(toolSlug.replace(/-/g, ' '));
// Segment drives every generated path/snippet; for a tool not in the registry
// yet, leave a visible placeholder the author must resolve.
const segment = graphTool?.segment ?? '<segment>';
const categorySlug = graphTool?.categorySlug ?? '<category-slug>';
const toolPath = `src/tools/${segment}/${toolSlug}`;
const abbr = toolSlug.split('-').map(t => t[0]).join('').slice(0, 3) || 'tt';

// Identifier names for generated registration snippets
const camel = toolSlug.replace(/-(\w)/g, (_, c: string) => c.toUpperCase());
const pascal = camel.charAt(0).toUpperCase() + camel.slice(1);

// Entities for the brief: junk-filter once more (older research.json may
// predate the extract-time filter), allowlisting the tool's own vocabulary.
const entityAllowlist = new Set<string>(toolSlug.split('-').filter(t => t.length > 2));
for (const t of graphTool?.tags ?? []) {
  entityAllowlist.add(t.toLowerCase());
  t.toLowerCase().split(/\s+/).forEach(w => w.length > 2 && entityAllowlist.add(w));
}
const briefEntities = doc.entities.filter(e => isSpecificEntity(e, entityAllowlist)).slice(0, 10);

// Question pool, deduped. Lead with questions that mention a slug token (the
// on-topic ones) so the draft surfaces relevant questions first and pushes
// competitor-specific noise ("What is Webhook?") below the cap.
const slugTokens = toolSlug.split('-').filter(t => t.length > 2);
const isOnTopic = (q: string) => slugTokens.some(tok => q.toLowerCase().includes(tok));

// Strip enumerator prefixes ("Q.", "1.") for display; dedupe on a normalized
// key so "What is the Pomodoro Technique?" and "Q. What is Pomodoro Technique?"
// collapse to one entry.
const cleanQuestion = (q: string) => q.replace(/^\s*(q[\.\):]|\d+[\.\)\:])\s*/i, '').trim();

// Reddit question + misconception clusters represent *real, high-demand* user
// questions — fold them into the FAQ pool (highest-engagement first) so authored
// FAQs answer what users actually ask, not just what competitors happen to cover.
const redditQuestions = (doc.redditQuestions ?? []).map(s => s.topic);
const redditMisconceptions = (doc.redditMisconceptions ?? []).map(s => s.topic);
const pool = [...redditQuestions, ...redditMisconceptions, ...doc.questions, ...doc.competitorFaqs]
  .map(q => q.trim())
  .filter(Boolean);
const seen = new Set<string>();
const questions: string[] = [];
for (const raw of [...pool.filter(isOnTopic), ...pool.filter(q => !isOnTopic(q))]) {
  const key = normalizeHeading(raw).replace(/\?+$/, '');
  if (!key || seen.has(key)) continue;
  seen.add(key);
  questions.push(cleanQuestion(raw));
  if (questions.length >= 12) break;
}

const outDir = join(ROOT, 'output', toolSlug);
mkdirSync(outDir, { recursive: true });

// ---- faq.draft.ts ----------------------------------------------------------
const faqItems = questions
  .map((q, i) => {
    const question = q.endsWith('?') ? q : `${q}?`;
    return `  {\n    id: '${abbr}-faq-${i + 1}',\n    question: ${JSON.stringify(question)},\n    answer: 'TODO: answer from the research brief.',\n  },`;
  })
  .join('\n');

const faqDraft = `import type { FAQItem } from '@data/types';

// DRAFT generated by \`seo:scaffold ${toolSlug}\` from research.json.
// Fill in each answer, prune off-topic questions, then move into
// ${toolPath}/faq.ts and register it per PROMPT.md.
export const items: FAQItem[] = [
${faqItems}
];
`;
writeFileSync(join(outDir, 'faq.draft.ts'), faqDraft);

// ---- guide.outline.md ------------------------------------------------------
const bullets = (arr: string[], empty: string) =>
  arr.length ? arr.map(s => `- ${s}`).join('\n') : `_${empty}_`;

// User-demand block, sourced from Reddit intent signals. These are *topics to
// address in original prose* — never Reddit text to reproduce.
const opportunities = (doc.contentOpportunities ?? []).map(o => `${o.topic} _(opportunity ${o.score})_`);
const comparisons = (doc.redditComparisons ?? []).map(s => s.topic);
const painPoints = (doc.redditPainPoints ?? []).map(s => s.topic);
const misconceptions = (doc.redditMisconceptions ?? []).map(s => s.topic);
const hasReddit = (doc.sampleSize ?? 0) > 0;

const userDemandSection = hasReddit
  ? `
## User demand (from Reddit intent — address as original prose, do NOT reproduce Reddit text)

> Demand ${doc.redditDemandScore}/100 · confidence ${doc.dataConfidence} (n=${doc.sampleSize})${doc.audienceTypes?.length ? ` · audience: ${doc.audienceTypes.join(', ')}` : ''}

**Ranked content opportunities**
${bullets(opportunities, 'None detected.')}

**Comparisons users make**
${bullets(comparisons, 'None detected.')}

**Pain points to troubleshoot**
${bullets(painPoints, 'None detected.')}

**Misconceptions to correct (strong GEO/FAQ opportunities)**
${bullets(misconceptions, 'None detected.')}
`
  : '';

const guideOutline = `# ${name} — Guide outline

> Generated by \`seo:scaffold ${toolSlug}\`. Section ordering is a starting point.

**Primary intent:** ${doc.primaryIntent} · **Secondary intent:** ${doc.secondaryIntent}

**Entities to mention:** ${briefEntities.join(', ') || '(none survived junk filtering)'}

## Table-stakes sections (competitor consensus)
${bullets(doc.competitorHeadings, 'No cross-site consensus formed — see related topics and gaps below.')}

## Differentiation — gaps competitors miss (lead with these)
${bullets(doc.contentGaps.slice(0, 12), 'None detected.')}
${userDemandSection}
## Related topics
${bullets(doc.relatedTopics, 'None detected.')}
`;
writeFileSync(join(outDir, 'guide.outline.md'), guideOutline);

// ---- knowledge.draft.ts ----------------------------------------------------
// Seeds the Phase D knowledge layer from research. Relationship fields (usedWith/
// alternatives/nextSteps) need human judgement about sibling tools, so they're left
// as TODO stubs with the RelationshipReference shape; everything else is pre-filled.
const useCases = (doc.redditUseCases ?? []).map(s => s.topic);
const terminology = (doc.redditTerminology ?? []).map(s => s.topic);
const jsArr = (arr: string[], n = 6) =>
  arr.slice(0, n).map(s => JSON.stringify(s)).join(', ');

const knowledgeDraft = `import { KNOWLEDGE_SCHEMA_VERSION, type Knowledge } from '@lib/knowledge/types';

// DRAFT generated by \`seo:scaffold ${toolSlug}\` from research.json.
// Fill the relationship fields (usedWith / alternatives / nextSteps) with real sibling
// tool slugs + a human \`reason\`, set workflowStage, then move to
// ${toolPath}/knowledge.ts and run \`npm run registries:generate\` (registration is derived).
export const knowledge: Knowledge = {
  schemaVersion: KNOWLEDGE_SCHEMA_VERSION,
  slug: ${JSON.stringify(toolSlug)},
  title: ${JSON.stringify(name)},
  category: ${JSON.stringify(categorySlug)},
  summary: 'TODO: one-line summary, max 160 chars.',
  primaryConcepts: [${jsArr(doc.entities, 2)}],
  secondaryConcepts: [${jsArr(doc.entities.slice(2), 5)}],
  intentGroups: {
    informational: [${jsArr(doc.questions, 4)}],
    howTo: [],
    comparison: [${jsArr(comparisons, 3)}],
    misconception: [${jsArr(misconceptions, 3)}],
    troubleshooting: [${jsArr(painPoints, 3)}],
  },
  realWorldUseCases: [${jsArr(useCases, 4)}],
  commonMistakes: [], // TODO from misconceptions / pain points
  commonQuestions: [${jsArr(questions, 3)}],
  usedWith: [], // TODO: [{ slug: 'sibling-tool', reason: 'why', strength: 0.8 }]
  alternatives: [], // TODO: [{ slug: 'alt-tool', reason: 'when to choose it' }]
  nextSteps: [], // TODO: [{ slug: 'next-tool', reason: 'what to do next', priority: 1 }]
  workflowStage: ['transform'], // TODO: input | transform | validate | analyze | export
  keywords: [${jsArr(doc.entities, 6)}],
  entityAliases: [${jsArr(terminology, 4)}],
};
`;
writeFileSync(join(outDir, 'knowledge.draft.ts'), knowledgeDraft);

// ---- PROMPT.md -------------------------------------------------------------
// The brief is self-contained on purpose: a model that has read nothing else
// must be able to produce passing content from this one file. Style rules are
// rendered from writing-rules.json and gates from content-intelligence-rules.json
// so the brief can never drift from what the audit enforces.

interface WritingRulesLite {
  sentenceLength: { ideal_min: number; ideal_max: number; long_max: number };
  maxParagraphSentences: number;
  exampleEveryWords: number;
  jargonWords: string[];
  jargonReplacements: Record<string, string>;
  hedgingWords: string[];
  fluffPhrases: string[];
  boringPhrases: string[];
  aiTellPhrases: string[];
}
const WR = JSON.parse(readFileSync(join(ROOT, 'config', 'writing-rules.json'), 'utf-8')) as WritingRulesLite;
const CI = JSON.parse(readFileSync(join(ROOT, 'config', 'content-intelligence-rules.json'), 'utf-8')) as {
  gates: { overall: number; minimums: Record<string, number> };
};

// A real section from an exemplar guide, captured at scaffold time so the
// shape shown is always the shape that currently ships.
const exemplarRel = 'src/tools/text/character-counter/Guide.astro';
let exemplarSnippet = '(exemplar not found; open the file listed above instead)';
const exemplarAbs = join(PROJECT, exemplarRel);
if (existsSync(exemplarAbs)) {
  const src = readFileSync(exemplarAbs, 'utf-8');
  const section = src.match(/<section id="quick-answer">[\s\S]*?<\/section>/);
  const refBlock = src.match(/<ReferenceBlock[\s\S]*?<\/ReferenceBlock>/);
  exemplarSnippet = [section?.[0], refBlock?.[0]].filter(Boolean).join('\n\n  ...\n\n');
}

const replacements = Object.entries(WR.jargonReplacements).map(([k, v]) => `${k} -> ${v}`).join(', ');
const minimums = Object.entries(CI.gates.minimums).map(([k, v]) => `${k} >= ${v}`).join(', ');
const today = new Date().toLocaleDateString('en-US', { month: 'short', year: 'numeric' });

const prompt = `# Authoring brief: ${name} (${toolSlug})

This brief is self-contained. Everything you need (style contract, file specs,
registration snippets, acceptance commands) is below. All commands run from the
project root.

## Goal and definition of done

Write (or improve) the guide, FAQ, and knowledge file for **${name}** in
\`${toolPath}/\`. You are done when all three hold:

1. \`Guide.astro\`, \`faq.ts\`, and \`knowledge.ts\` exist and are registered (snippets in section 7).
2. \`npm run build\` passes.
3. \`npm run seo:gate -- ${toolSlug}\` exits 0
   (overall >= ${CI.gates.overall}; ${minimums}; zero high-impact actions, zero AI-tell phrases, zero em-dashes).

## 1. Style contract (the audit enforces every line of this)

- Sentences: average ${WR.sentenceLength.ideal_min}-${WR.sentenceLength.ideal_max} words, never more than ${WR.sentenceLength.long_max}. Vary lengths; identical-length runs read as machine output.
- Paragraphs: max ${WR.maxParagraphSentences} sentences, one idea each. Vary paragraph sizes too; six same-shaped paragraphs in a row is an AI tell.
- One concrete example roughly every ${WR.exampleEveryWords} words. Real values ("Input: HELLO -> Output: hello"), never hypothetical X and Y.
- At least 3 headings phrased as questions. The first sentence after every heading answers it directly in under 25 words.
- Active voice ("the tool counts characters", not "characters are counted"). Hedge ("may", "might") only when genuinely uncertain.
- **Never use an em-dash anywhere.** Use a period, comma, colon, or parentheses instead. One em-dash fails the gate.
- Never write "not just X, it's Y", "not only ... but", or any contrast-reveal framing. State the fact.
- Avoid "A, B, and C" triplet lists in more than a quarter of sentences.
- Banned jargon: ${WR.jargonWords.join(', ')}. Replacements: ${replacements}.
- Banned AI-tell vocabulary: ${WR.aiTellPhrases.join(', ')}.
- Banned fluff: ${[...WR.fluffPhrases, ...WR.boringPhrases].join('; ')}.
- Plain English for an intelligent non-specialist; define technical terms inline on first use.

## 2. Write like these files

Open and imitate (structure, tone, density):

- \`src/tools/developer/json-formatter/Guide.astro\`
- \`${exemplarRel}\`

Section shape from the second exemplar:

\`\`\`astro
${exemplarSnippet}
\`\`\`

## 3. Guide spec

File: \`${toolPath}/Guide.astro\` (wrap everything in \`GuideLayout\`, same frontmatter pattern as the exemplars).

- Every section: \`<section id="kebab-case-id">\` + \`<h2>Title <span class="gold-dot" aria-hidden="true"></span></h2>\`.
- Sections: Quick Answer first (definition + who it is for + CTA), then 3-5 conceptual sections, then Common Mistakes (2-3 \`<ReferenceBlock type="common-mistake">\` blocks), then optionally History.
- Cover all six first principles: what it is, why it matters, how it works, examples, common mistakes, comparisons.
- The CTA button (\`.cta-link\`, copied from the exemplar including its \`<style>\` block) links to the tool page via \`withBase\` and the \`/tool/${segment}/${toolSlug}/\` URL (singular \`/tool/\`).
- Use \`guide.outline.md\` in this directory for what to cover: do the table-stakes sections, but **lead with the differentiation gaps**; that is where this page can outrank competitors.
- Mention these entities where natural (inline, never as a list): ${briefEntities.join(', ') || '(none; use the tool name and its core concepts)'}.
- Target 1,100-2,600 words.

## 4. FAQ spec

File: \`${toolPath}/faq.ts\`. Start from \`faq.draft.ts\` in this directory.

- Export \`const items: FAQItem[]\` (import the type from \`@data/types\`).
- 8-12 items, ids \`${abbr}-faq-1\` ... in order.
- Answers are single plain strings, 40-80 words, no markdown, no bullets, no links. Include a concrete number or scenario where it helps. End with practical advice when possible.
- Drop draft questions that are off-topic (competitor product names, unrelated tech).

## 5. knowledge.ts spec

File: \`${toolPath}/knowledge.ts\`. Start from \`knowledge.draft.ts\` in this directory.

- \`slug\` must equal \`${JSON.stringify(toolSlug)}\` and \`category\` must equal \`${JSON.stringify(categorySlug)}\`; \`summary\` max 160 chars.
- Author only the overlay: concepts, intentGroups, realWorldUseCases, commonMistakes, commonQuestions, and the curated relations \`usedWith\`/\`alternatives\`/\`nextSteps\` with real sibling tool slugs plus a human \`reason\`. Related tools/guides/FAQs are derived automatically; do not author them.
- An invalid knowledge file fails the build; a missing one only warns.

## 6. Knowledge sync rules (the audit checks these)

- Every \`commonQuestions\` entry must have a matching question in \`faq.ts\`.
- Every \`commonMistakes\` topic must appear in the guide (a \`common-mistake\` ReferenceBlock).
- Every \`realWorldUseCases\` entry must be mentioned in the guide or an FAQ answer.

## 7. Registration (exact snippets for this tool)

a) \`${toolPath}/config.ts\`: add the \`guide\` field (there is **no** \`faq\` config field; FAQs register only in step d):

\`\`\`ts
guide: {
  slug: 'TODO-guide-slug',          // kebab-case topic slug, e.g. 'what-is-${toolSlug}'
  categorySlug: '${segment}',
  title: 'TODO guide title',
  description: 'TODO, 160 chars max.',
  readMinutes: 4,
  updatedAt: '${today}',
},
\`\`\`

b) Regenerate the derived registration barrels (registration follows from the files you
   authored in \`src/tools/${segment}/${toolSlug}/\` — never hand-edit \`registry.ts\`,
   \`faq-registry.ts\`, \`guide-registry.ts\`, \`knowledge/registry.ts\`, any \`*.generated.ts\`,
   or the guide route):

\`\`\`sh
npm run registries:generate
\`\`\`
${hasReddit ? `
## 8. User demand (Reddit intent)

The "User demand" section of \`guide.outline.md\` lists what real users ask,
compare, and misunderstand (demand ${doc.redditDemandScore}/100, n=${doc.sampleSize}). Prioritise
the ranked opportunities and answer the misconceptions explicitly; those are
exactly the Q&A blocks answer engines surface.

**Hard rule:** these are research signals for *what to cover*. Write everything
in your own original prose. Never copy, paraphrase, or rephrase Reddit titles,
posts, or comments into the published content.
` : ''}
## The loop (run until done)

1. Write the three files; apply the registration snippets.
2. \`npm run build\` (fix any errors).
3. \`npm run seo:gate -- ${toolSlug}\`
4. If the gate fails: read \`seo-engine/reports/tool-content-intelligence-${toolSlug}.json\`, apply the High Impact actions (then Medium), and go to 2. Maximum 3 iterations; if still failing, stop and report the remaining actions instead of looping.
5. If any command behaves unexpectedly, run \`npm run seo:doctor\` and fix what it reports.
`;
writeFileSync(join(outDir, 'PROMPT.md'), prompt);

console.log(`\n=== Scaffolded ${toolSlug} ===`);
console.log(`  ${questions.length} questions → output/${toolSlug}/faq.draft.ts`);
console.log(`  Knowledge stub   → output/${toolSlug}/knowledge.draft.ts`);
console.log(`  Guide outline    → output/${toolSlug}/guide.outline.md`);
console.log(`  Agent prompt     → output/${toolSlug}/PROMPT.md`);
console.log(`\nHand PROMPT.md to Claude Code, or fill the drafts yourself.\n`);
