// @ts-check
import { defineConfig } from 'astro/config';

const base = process.env.ASTRO_BASE_PATH;

/** @type {import('astro/config').AstroIntegration} */
const routeManifest = {
  name: 'route-manifest',
  hooks: {
    'astro:build:done': async ({ dir, pages }) => {
      const { writeFileSync } = await import('node:fs');
      const routes = pages.map(p => {
        // 404 page is generated as 404.html, not 404/index.html
        if (p.pathname === '404' || p.pathname === '404/') return '/404.html';
        return `/${p.pathname}`.replace(/\/{2,}/g, '/');
      });
      const manifest = { generated: new Date().toISOString(), routes };
      writeFileSync(new URL('route-manifest.json', dir), JSON.stringify(manifest, null, 2));
    },
  },
};

/** @type {import('astro/config').AstroIntegration} */
const seoValidator = {
  name: 'seo-validator',
  hooks: {
    'astro:build:done': async ({ dir }) => {
      const { existsSync } = await import('node:fs');
      const d = new URL(dir).pathname;
      const missing = ['robots.txt', 'sitemap-index.xml'].filter(f => !existsSync(d + f));
      if (missing.length) throw new Error(`SEO build validation failed — missing: ${missing.join(', ')}`);
    },
  },
};

export default defineConfig({
  integrations: [
    routeManifest,
    // Sitemap is generated by registry-driven endpoints (src/pages/sitemap-index.xml.ts +
    // src/pages/sitemaps/*.xml.ts), not @astrojs/sitemap. See ARCHITECTURE.md → Sitemap.
    seoValidator,
    // No Partytown. It was configured to forward dataLayer.push, but nothing on the site is ever
    // marked type="text/partytown" — Google Analytics is injected as an ordinary async script by
    // src/lib/runtime/platform.ts, behind the analytics guard. So the integration intercepted
    // nothing while still putting a ~4 KB parser-blocking loader in every page's <head> and
    // fetching a sandbox iframe. If GA is ever moved onto a worker, re-add it AND mark the GA
    // script type="text/partytown", or it will be dead weight again.
  ],
  site: process.env.ASTRO_SITE ?? 'https://toytoolsapp.com',
  base,
  output: 'static',
  trailingSlash: 'always',
  compressHTML: true,
  build: {
    assets: '_assets',
    inlineStylesheets: 'auto',
  },
});
