import type { ToolConfig } from '@data/types';

export const config: ToolConfig = {
  slug: 'equalizer-settings-generator',
  name: 'Music Equalizer Settings',
  seoTitle: 'Music Equalizer Settings Generator',
  description: 'Turn more bass or clearer vocals into equalizer settings: tune seven bands from 60 Hz to 15 kHz, load a bass booster curve, copy the dB into your player.',
  tagline: 'Find your sound, then copy the numbers into your own player.',
  categorySlug: 'music-audio',
  tags: [
    'equalizer settings',
    'music equalizer',
    'eq settings',
    'best eq settings for bass',
    'eq settings for vocals',
    'bass boost eq',
    'equalizer presets',
    'eq frequency chart',
    'what does 60 hz do',
    'how to set an equalizer',
    'graphic eq',
    'eq curve',
  ],
  isNew: true,
  updatedAt: '2026-08-30',
  engine: 'audio',
  pattern: 'eq-design',
  family: 'equalizer',
  processorId: 'music-eq-7',
  craft: {
    id: 'eq-preamp-headroom',
    kind: 'guardrail',
    solves: 'A curve built out of boosts pushes a player past full scale, and the crackle that follows on the loudest parts gets blamed on the headphones or the file. The control that fixes it is a preamp cut of the same size, which sits on a different screen in most players and is never labelled as the thing that fixes this.',
  },
  relatedTools: ['frequency-period-calculator', 'wave-speed-calculator'],
  guide: {
    slug: 'how-to-set-an-equalizer',
    categorySlug: 'music',
    title: 'How to Set an Equalizer: What Each Frequency Does',
    description: 'What each EQ band changes, how to get more bass or clearer vocals without making a mess, and why the same settings sound different on different headphones.',
    readMinutes: 8,
    updatedAt: '2026-08-30',
  },
};
