import type { ToolConfig } from '@data/types';

export const config: ToolConfig = {
  slug: 'equalizer-settings-generator',
  name: 'Music Equalizer Settings',
  seoTitle: 'Music Equalizer Settings Generator',
  description: 'Build music equalizer settings from what you want to hear. Pick a goal like more bass or clearer vocals, drag the seven bands from 60 Hz to 15 kHz, and see what each frequency changes. Load EQ presets from a bass booster curve to a late-night one, then copy the dB values into the sound settings in Spotify, on your phone, in your headphones app or in your car.',
  tagline: 'Find your sound, then copy the numbers into your own player.',
  categorySlug: 'music-audio',
  tags: [
    'equalizer settings',
    'music equalizer',
    'eq settings',
    'best eq settings for bass',
    'eq settings for vocals',
    'bass boost eq',
    'equalizer presets',
    'eq frequency chart',
    'what does 60 hz do',
    'how to set an equalizer',
    'graphic eq',
    'eq curve',
  ],
  isNew: true,
  updatedAt: '2026-08-30',
  engine: 'audio',
  pattern: 'eq-design',
  family: 'equalizer',
  processorId: 'music-eq-7',
  craft: {
    id: 'eq-preamp-headroom',
    kind: 'guardrail',
    solves: 'A curve built out of boosts pushes a player past full scale, and the crackle that follows on the loudest parts gets blamed on the headphones or the file. The control that fixes it is a preamp cut of the same size, which sits on a different screen in most players and is never labelled as the thing that fixes this.',
  },
  relatedTools: ['frequency-period-calculator', 'wave-speed-calculator'],
  guide: {
    slug: 'how-to-set-an-equalizer',
    categorySlug: 'music',
    title: 'How to Set an Equalizer: What Each Frequency Band Does',
    description: 'What each EQ band changes, how to get more bass or clearer vocals without making a mess, and why the same settings sound different on different headphones.',
    readMinutes: 8,
    updatedAt: '2026-08-30',
  },
};
