// Character Map — the catalogue of characters the map renders.
//
// Data, not logic: the widget imports this at build time and prints a grid, so no character table
// ships in a script and no name is worked out in the browser. Names come from the Unicode standard,
// trimmed of the parts that read as noise in a picker ("Latin Small Letter E With Acute" is filed as
// "E With Acute", because the grid it sits in already says which alphabet you are looking at).
//
// `entity` holds the named HTML entity where one exists. Everything else falls back to the numeric
// form, which is derived rather than stored, since it is just the code point in hex.

export interface MapCharacter {
  /** The character itself. */
  char: string;
  /** Human-readable name, used for search and for the detail line. */
  name: string;
  /** Named HTML entity without the ampersand and semicolon, when the character has one. */
  entity?: string;
}

export interface CharacterGroup {
  /** Group heading, also the filter label. */
  name: string;
  /** One line saying what belongs in this group. */
  description: string;
  characters: MapCharacter[];
}

export const characterGroups: CharacterGroup[] = [
  {
    name: 'Punctuation',
    description: 'Dashes, quotes, ellipses and the marks that a word processor swaps in',
    characters: [
      { char: '…', name: 'Horizontal Ellipsis', entity: 'hellip' },
      { char: '–', name: 'EN Dash', entity: 'ndash' },
      { char: '—', name: 'EM Dash', entity: 'mdash' },
      { char: '‑', name: 'Non-breaking Hyphen' },
      { char: '‘', name: 'Left Single Quotation Mark', entity: 'lsquo' },
      { char: '’', name: 'Right Single Quotation Mark', entity: 'rsquo' },
      { char: '‚', name: 'Single Low-9 Quotation Mark', entity: 'sbquo' },
      { char: '“', name: 'Left Double Quotation Mark', entity: 'ldquo' },
      { char: '”', name: 'Right Double Quotation Mark', entity: 'rdquo' },
      { char: '„', name: 'Double Low-9 Quotation Mark', entity: 'bdquo' },
      { char: '«', name: 'Left-pointing Double Angle Quotation Mark', entity: 'laquo' },
      { char: '»', name: 'Right-pointing Double Angle Quotation Mark', entity: 'raquo' },
      { char: '‹', name: 'Single Left-pointing Angle Quotation Mark', entity: 'lsaquo' },
      { char: '›', name: 'Single Right-pointing Angle Quotation Mark', entity: 'rsaquo' },
      { char: '†', name: 'Dagger', entity: 'dagger' },
      { char: '‡', name: 'Double Dagger', entity: 'Dagger' },
      { char: '•', name: 'Bullet', entity: 'bull' },
      { char: '‣', name: 'Triangular Bullet' },
      { char: '·', name: 'Middle Dot', entity: 'middot' },
      { char: '¶', name: 'Pilcrow Sign', entity: 'para' },
      { char: '§', name: 'Section Sign', entity: 'sect' },
      { char: '¡', name: 'Inverted Exclamation Mark', entity: 'iexcl' },
      { char: '¿', name: 'Inverted Question Mark', entity: 'iquest' },
      { char: '‰', name: 'Per Mille Sign', entity: 'permil' },
      { char: '′', name: 'Prime', entity: 'prime' },
      { char: '″', name: 'Double Prime', entity: 'Prime' },
      { char: '‴', name: 'Triple Prime' },
      { char: '⁄', name: 'Fraction Slash', entity: 'frasl' },
    ],
  },
  {
    name: 'Currency',
    description: 'Symbols for money, including the ones no keyboard has',
    characters: [
      { char: '$', name: 'Dollar Sign' },
      { char: '¢', name: 'Cent Sign', entity: 'cent' },
      { char: '£', name: 'Pound Sign', entity: 'pound' },
      { char: '¤', name: 'Currency Sign', entity: 'curren' },
      { char: '¥', name: 'Yen Sign', entity: 'yen' },
      { char: '€', name: 'Euro Sign', entity: 'euro' },
      { char: '₹', name: 'Indian Rupee Sign' },
      { char: '₽', name: 'Ruble Sign' },
      { char: '₩', name: 'Won Sign' },
      { char: '₪', name: 'New Sheqel Sign' },
      { char: '₫', name: 'Dong Sign' },
      { char: '₱', name: 'Peso Sign' },
      { char: '₲', name: 'Guarani Sign' },
      { char: '₴', name: 'Hryvnia Sign' },
      { char: '₵', name: 'Cedi Sign' },
      { char: '₸', name: 'Tenge Sign' },
      { char: '₺', name: 'Turkish Lira Sign' },
      { char: '₼', name: 'Manat Sign' },
      { char: '₾', name: 'Lari Sign' },
      { char: '₿', name: 'Bitcoin Sign' },
      { char: 'ƒ', name: 'F With Hook', entity: 'fnof' },
    ],
  },
  {
    name: 'Math',
    description: 'Operators, comparisons and set notation',
    characters: [
      { char: '×', name: 'Multiplication Sign', entity: 'times' },
      { char: '÷', name: 'Division Sign', entity: 'divide' },
      { char: '±', name: 'Plus-minus Sign', entity: 'plusmn' },
      { char: '∓', name: 'Minus-or-plus Sign' },
      { char: '≈', name: 'Almost Equal TO', entity: 'asymp' },
      { char: '≉', name: 'Not Almost Equal TO' },
      { char: '≠', name: 'Not Equal TO', entity: 'ne' },
      { char: '≡', name: 'Identical TO', entity: 'equiv' },
      { char: '≤', name: 'Less-than OR Equal TO', entity: 'le' },
      { char: '≥', name: 'Greater-than OR Equal TO', entity: 'ge' },
      { char: '≪', name: 'Much Less-than' },
      { char: '≫', name: 'Much Greater-than' },
      { char: '∞', name: 'Infinity', entity: 'infin' },
      { char: '√', name: 'Square Root', entity: 'radic' },
      { char: '∛', name: 'Cube Root' },
      { char: '∑', name: 'N-ary Summation', entity: 'sum' },
      { char: '∏', name: 'N-ary Product', entity: 'prod' },
      { char: '∫', name: 'Integral', entity: 'int' },
      { char: '∂', name: 'Partial Differential', entity: 'part' },
      { char: '∆', name: 'Increment' },
      { char: '∇', name: 'Nabla', entity: 'nabla' },
      { char: '∈', name: 'Element OF', entity: 'isin' },
      { char: '∉', name: 'Not AN Element OF', entity: 'notin' },
      { char: '⊂', name: 'Subset OF', entity: 'sub' },
      { char: '⊃', name: 'Superset OF', entity: 'sup' },
      { char: '⊆', name: 'Subset OF OR Equal TO', entity: 'sube' },
      { char: '⊇', name: 'Superset OF OR Equal TO', entity: 'supe' },
      { char: '∪', name: 'Union', entity: 'cup' },
      { char: '∩', name: 'Intersection', entity: 'cap' },
      { char: '∀', name: 'For All', entity: 'forall' },
      { char: '∃', name: 'There Exists', entity: 'exist' },
      { char: '∄', name: 'There Does Not Exist' },
      { char: '¬', name: 'Not Sign', entity: 'not' },
      { char: '∧', name: 'Logical And', entity: 'and' },
      { char: '∨', name: 'Logical OR', entity: 'or' },
      { char: '⊕', name: 'Circled Plus', entity: 'oplus' },
      { char: '⊗', name: 'Circled Times', entity: 'otimes' },
      { char: '∴', name: 'Therefore', entity: 'there4' },
      { char: '∵', name: 'Because' },
      { char: '∝', name: 'Proportional TO', entity: 'prop' },
      { char: '∅', name: 'Empty Set', entity: 'empty' },
      { char: '°', name: 'Degree Sign', entity: 'deg' },
      { char: 'µ', name: 'Micro Sign', entity: 'micro' },
    ],
  },
  {
    name: 'Arrows',
    description: 'Directions, returns and pointers',
    characters: [
      { char: '←', name: 'Leftwards Arrow', entity: 'larr' },
      { char: '↑', name: 'Upwards Arrow', entity: 'uarr' },
      { char: '→', name: 'Rightwards Arrow', entity: 'rarr' },
      { char: '↓', name: 'Downwards Arrow', entity: 'darr' },
      { char: '↔', name: 'Left Right Arrow', entity: 'harr' },
      { char: '↕', name: 'UP Down Arrow' },
      { char: '↖', name: 'North West Arrow' },
      { char: '↗', name: 'North East Arrow' },
      { char: '↘', name: 'South East Arrow' },
      { char: '↙', name: 'South West Arrow' },
      { char: '⇐', name: 'Leftwards Double Arrow', entity: 'lArr' },
      { char: '⇑', name: 'Upwards Double Arrow', entity: 'uArr' },
      { char: '⇒', name: 'Rightwards Double Arrow', entity: 'rArr' },
      { char: '⇓', name: 'Downwards Double Arrow', entity: 'dArr' },
      { char: '⇔', name: 'Left Right Double Arrow', entity: 'hArr' },
      { char: '↩', name: 'Leftwards Arrow With Hook' },
      { char: '↪', name: 'Rightwards Arrow With Hook' },
      { char: '↺', name: 'Anticlockwise Open Circle Arrow' },
      { char: '↻', name: 'Clockwise Open Circle Arrow' },
      { char: '⇄', name: 'Rightwards Arrow Over Leftwards Arrow' },
      { char: '⇅', name: 'Upwards Arrow Leftwards OF Downwards Arrow' },
      { char: '➜', name: 'Heavy Round-tipped Rightwards Arrow' },
      { char: '➔', name: 'Heavy Wide-headed Rightwards Arrow' },
      { char: '▶', name: 'Black Right-pointing Triangle' },
      { char: '◀', name: 'Black Left-pointing Triangle' },
      { char: '▲', name: 'Black Up-pointing Triangle' },
      { char: '▼', name: 'Black Down-pointing Triangle' },
    ],
  },
  {
    name: 'Greek',
    description: 'The Greek alphabet, as used in maths and science',
    characters: [
      { char: 'α', name: 'Greek Alpha' },
      { char: 'β', name: 'Greek Beta' },
      { char: 'γ', name: 'Greek Gamma' },
      { char: 'δ', name: 'Greek Delta' },
      { char: 'ε', name: 'Greek Epsilon' },
      { char: 'ζ', name: 'Greek Zeta' },
      { char: 'η', name: 'Greek Eta' },
      { char: 'θ', name: 'Greek Theta' },
      { char: 'ι', name: 'Greek Iota' },
      { char: 'κ', name: 'Greek Kappa' },
      { char: 'λ', name: 'Greek Lamda' },
      { char: 'μ', name: 'Greek MU' },
      { char: 'ν', name: 'Greek NU' },
      { char: 'ξ', name: 'Greek XI' },
      { char: 'ο', name: 'Greek Omicron' },
      { char: 'π', name: 'Greek PI' },
      { char: 'ρ', name: 'Greek Rho' },
      { char: 'σ', name: 'Greek Sigma' },
      { char: 'τ', name: 'Greek Tau' },
      { char: 'υ', name: 'Greek Upsilon' },
      { char: 'φ', name: 'Greek Phi' },
      { char: 'χ', name: 'Greek Chi' },
      { char: 'ψ', name: 'Greek Psi' },
      { char: 'ω', name: 'Greek Omega' },
      { char: 'Α', name: 'Greek capital Alpha' },
      { char: 'Β', name: 'Greek capital Beta' },
      { char: 'Γ', name: 'Greek capital Gamma' },
      { char: 'Δ', name: 'Greek capital Delta' },
      { char: 'Ε', name: 'Greek capital Epsilon' },
      { char: 'Ζ', name: 'Greek capital Zeta' },
      { char: 'Η', name: 'Greek capital Eta' },
      { char: 'Θ', name: 'Greek capital Theta' },
      { char: 'Ι', name: 'Greek capital Iota' },
      { char: 'Κ', name: 'Greek capital Kappa' },
      { char: 'Λ', name: 'Greek capital Lamda' },
      { char: 'Μ', name: 'Greek capital MU' },
      { char: 'Ν', name: 'Greek capital NU' },
      { char: 'Ξ', name: 'Greek capital XI' },
      { char: 'Ο', name: 'Greek capital Omicron' },
      { char: 'Π', name: 'Greek capital PI' },
      { char: 'Ρ', name: 'Greek capital Rho' },
      { char: 'Σ', name: 'Greek capital Sigma' },
      { char: 'Τ', name: 'Greek capital Tau' },
      { char: 'Υ', name: 'Greek capital Upsilon' },
      { char: 'Φ', name: 'Greek capital Phi' },
      { char: 'Χ', name: 'Greek capital Chi' },
      { char: 'Ψ', name: 'Greek capital Psi' },
      { char: 'Ω', name: 'Greek capital Omega' },
    ],
  },
  {
    name: 'Accented Latin',
    description: 'Letters with diacritics, and the ligatures that come with them',
    characters: [
      { char: 'á', name: 'A With Acute' },
      { char: 'à', name: 'A With Grave' },
      { char: 'â', name: 'A With Circumflex' },
      { char: 'ä', name: 'A With Diaeresis' },
      { char: 'ã', name: 'A With Tilde' },
      { char: 'å', name: 'A With Ring Above' },
      { char: 'ā', name: 'A With Macron' },
      { char: 'ă', name: 'A With Breve' },
      { char: 'ą', name: 'A With Ogonek' },
      { char: 'æ', name: 'AE', entity: 'aelig' },
      { char: 'ç', name: 'C With Cedilla', entity: 'ccedil' },
      { char: 'ć', name: 'C With Acute' },
      { char: 'č', name: 'C With Caron' },
      { char: 'ď', name: 'D With Caron' },
      { char: 'đ', name: 'D With Stroke' },
      { char: 'é', name: 'E With Acute' },
      { char: 'è', name: 'E With Grave' },
      { char: 'ê', name: 'E With Circumflex' },
      { char: 'ë', name: 'E With Diaeresis' },
      { char: 'ē', name: 'E With Macron' },
      { char: 'ė', name: 'E With Dot Above' },
      { char: 'ę', name: 'E With Ogonek' },
      { char: 'ě', name: 'E With Caron' },
      { char: 'ğ', name: 'G With Breve' },
      { char: 'í', name: 'I With Acute' },
      { char: 'ì', name: 'I With Grave' },
      { char: 'î', name: 'I With Circumflex' },
      { char: 'ï', name: 'I With Diaeresis' },
      { char: 'ī', name: 'I With Macron' },
      { char: 'į', name: 'I With Ogonek' },
      { char: 'ı', name: 'Dotless I' },
      { char: 'ñ', name: 'N With Tilde', entity: 'ntilde' },
      { char: 'ń', name: 'N With Acute' },
      { char: 'ň', name: 'N With Caron' },
      { char: 'ó', name: 'O With Acute' },
      { char: 'ò', name: 'O With Grave' },
      { char: 'ô', name: 'O With Circumflex' },
      { char: 'ö', name: 'O With Diaeresis' },
      { char: 'õ', name: 'O With Tilde' },
      { char: 'ø', name: 'O With Stroke', entity: 'oslash' },
      { char: 'ō', name: 'O With Macron' },
      { char: 'œ', name: 'Latin Small Ligature OE', entity: 'oelig' },
      { char: 'ŕ', name: 'R With Acute' },
      { char: 'ř', name: 'R With Caron' },
      { char: 'ś', name: 'S With Acute' },
      { char: 'š', name: 'S With Caron', entity: 'scaron' },
      { char: 'ş', name: 'S With Cedilla' },
      { char: 'ß', name: 'Sharp S', entity: 'szlig' },
      { char: 'ť', name: 'T With Caron' },
      { char: 'ú', name: 'U With Acute' },
      { char: 'ù', name: 'U With Grave' },
      { char: 'û', name: 'U With Circumflex' },
      { char: 'ü', name: 'U With Diaeresis' },
      { char: 'ū', name: 'U With Macron' },
      { char: 'ů', name: 'U With Ring Above' },
      { char: 'ý', name: 'Y With Acute' },
      { char: 'ÿ', name: 'Y With Diaeresis', entity: 'yuml' },
      { char: 'ź', name: 'Z With Acute' },
      { char: 'ž', name: 'Z With Caron' },
      { char: 'ż', name: 'Z With Dot Above' },
      { char: 'þ', name: 'Thorn', entity: 'thorn' },
      { char: 'ð', name: 'Eth', entity: 'eth' },
      { char: 'ł', name: 'L With Stroke' },
    ],
  },
  {
    name: 'Symbols',
    description: 'Legal marks, ticks, boxes, suits and keyboard keys',
    characters: [
      { char: '©', name: 'Copyright Sign', entity: 'copy' },
      { char: '®', name: 'Registered Sign', entity: 'reg' },
      { char: '™', name: 'Trade Mark Sign', entity: 'trade' },
      { char: '℠', name: 'Service Mark' },
      { char: '℗', name: 'Sound Recording Copyright' },
      { char: '№', name: 'Numero Sign' },
      { char: '℮', name: 'Estimated Symbol' },
      { char: '★', name: 'Black Star' },
      { char: '☆', name: 'White Star' },
      { char: '✦', name: 'Black Four Pointed Star' },
      { char: '✧', name: 'White Four Pointed Star' },
      { char: '✓', name: 'Check Mark' },
      { char: '✔', name: 'Heavy Check Mark' },
      { char: '✗', name: 'Ballot X' },
      { char: '✘', name: 'Heavy Ballot X' },
      { char: '☐', name: 'Ballot Box' },
      { char: '☑', name: 'Ballot Box With Check' },
      { char: '☒', name: 'Ballot Box With X' },
      { char: '♠', name: 'Black Spade Suit', entity: 'spades' },
      { char: '♥', name: 'Black Heart Suit', entity: 'hearts' },
      { char: '♦', name: 'Black Diamond Suit', entity: 'diams' },
      { char: '♣', name: 'Black Club Suit', entity: 'clubs' },
      { char: '♪', name: 'Eighth Note' },
      { char: '♫', name: 'Beamed Eighth Notes' },
      { char: '♭', name: 'Music Flat Sign' },
      { char: '♯', name: 'Music Sharp Sign' },
      { char: '☀', name: 'Black Sun With Rays' },
      { char: '☁', name: 'Cloud' },
      { char: '☂', name: 'Umbrella' },
      { char: '☃', name: 'Snowman' },
      { char: '⚠', name: 'Warning Sign' },
      { char: '⚡', name: 'High Voltage Sign' },
      { char: '☺', name: 'White Smiling Face' },
      { char: '☻', name: 'Black Smiling Face' },
      { char: '♀', name: 'Female Sign' },
      { char: '♂', name: 'Male Sign' },
      { char: '⌘', name: 'Place OF Interest Sign' },
      { char: '⌥', name: 'Option Key' },
      { char: '⇧', name: 'Upwards White Arrow' },
      { char: '⌃', name: 'UP Arrowhead' },
      { char: '⌫', name: 'Erase TO The Left' },
      { char: '⌦', name: 'Erase TO The Right' },
      { char: '⏎', name: 'Return Symbol' },
      { char: '⌤', name: 'UP Arrowhead Between Two Horizontal Bars' },
      { char: '␣', name: 'Open Box' },
      { char: '⏻', name: 'Power Symbol' },
      { char: '⏱', name: 'Stopwatch' },
      { char: '⏳', name: 'Hourglass With Flowing Sand' },
      { char: '✉', name: 'Envelope' },
      { char: '✂', name: 'Black Scissors' },
      { char: '✱', name: 'Heavy Asterisk' },
      { char: '❄', name: 'Snowflake' },
    ],
  },
  {
    name: 'Fractions',
    description: 'Vulgar fractions, superscripts and subscripts',
    characters: [
      { char: '½', name: 'Vulgar Fraction One Half', entity: 'frac12' },
      { char: '⅓', name: 'Vulgar Fraction One Third' },
      { char: '⅔', name: 'Vulgar Fraction Two Thirds' },
      { char: '¼', name: 'Vulgar Fraction One Quarter', entity: 'frac14' },
      { char: '¾', name: 'Vulgar Fraction Three Quarters', entity: 'frac34' },
      { char: '⅕', name: 'Vulgar Fraction One Fifth' },
      { char: '⅖', name: 'Vulgar Fraction Two Fifths' },
      { char: '⅗', name: 'Vulgar Fraction Three Fifths' },
      { char: '⅘', name: 'Vulgar Fraction Four Fifths' },
      { char: '⅙', name: 'Vulgar Fraction One Sixth' },
      { char: '⅚', name: 'Vulgar Fraction Five Sixths' },
      { char: '⅐', name: 'Vulgar Fraction One Seventh' },
      { char: '⅛', name: 'Vulgar Fraction One Eighth' },
      { char: '⅜', name: 'Vulgar Fraction Three Eighths' },
      { char: '⅝', name: 'Vulgar Fraction Five Eighths' },
      { char: '⅞', name: 'Vulgar Fraction Seven Eighths' },
      { char: '⅑', name: 'Vulgar Fraction One Ninth' },
      { char: '⅒', name: 'Vulgar Fraction One Tenth' },
      { char: '⁰', name: 'Superscript Zero' },
      { char: '¹', name: 'Superscript One', entity: 'sup1' },
      { char: '²', name: 'Superscript Two', entity: 'sup2' },
      { char: '³', name: 'Superscript Three', entity: 'sup3' },
      { char: '⁴', name: 'Superscript Four' },
      { char: '⁵', name: 'Superscript Five' },
      { char: '⁶', name: 'Superscript Six' },
      { char: '⁷', name: 'Superscript Seven' },
      { char: '⁸', name: 'Superscript Eight' },
      { char: '⁹', name: 'Superscript Nine' },
      { char: '⁺', name: 'Superscript Plus Sign' },
      { char: '⁻', name: 'Superscript Minus' },
      { char: '₀', name: 'Subscript Zero' },
      { char: '₁', name: 'Subscript One' },
      { char: '₂', name: 'Subscript Two' },
      { char: '₃', name: 'Subscript Three' },
      { char: '₄', name: 'Subscript Four' },
      { char: '₅', name: 'Subscript Five' },
      { char: '₆', name: 'Subscript Six' },
      { char: '₇', name: 'Subscript Seven' },
      { char: '₈', name: 'Subscript Eight' },
      { char: '₉', name: 'Subscript Nine' },
    ],
  },
  {
    name: 'Box drawing',
    description: 'Lines, corners and blocks for terminal art and diagrams',
    characters: [
      { char: '─', name: 'Box Light Horizontal' },
      { char: '│', name: 'Box Light Vertical' },
      { char: '┌', name: 'Box Light Down And Right' },
      { char: '┐', name: 'Box Light Down And Left' },
      { char: '└', name: 'Box Light UP And Right' },
      { char: '┘', name: 'Box Light UP And Left' },
      { char: '├', name: 'Box Light Vertical And Right' },
      { char: '┤', name: 'Box Light Vertical And Left' },
      { char: '┬', name: 'Box Light Down And Horizontal' },
      { char: '┴', name: 'Box Light UP And Horizontal' },
      { char: '┼', name: 'Box Light Vertical And Horizontal' },
      { char: '━', name: 'Box Heavy Horizontal' },
      { char: '┃', name: 'Box Heavy Vertical' },
      { char: '┏', name: 'Box Heavy Down And Right' },
      { char: '┓', name: 'Box Heavy Down And Left' },
      { char: '┗', name: 'Box Heavy UP And Right' },
      { char: '┛', name: 'Box Heavy UP And Left' },
      { char: '═', name: 'Box Double Horizontal' },
      { char: '║', name: 'Box Double Vertical' },
      { char: '╔', name: 'Box Double Down And Right' },
      { char: '╗', name: 'Box Double Down And Left' },
      { char: '╚', name: 'Box Double UP And Right' },
      { char: '╝', name: 'Box Double UP And Left' },
      { char: '╠', name: 'Box Double Vertical And Right' },
      { char: '╣', name: 'Box Double Vertical And Left' },
      { char: '╦', name: 'Box Double Down And Horizontal' },
      { char: '╩', name: 'Box Double UP And Horizontal' },
      { char: '╬', name: 'Box Double Vertical And Horizontal' },
      { char: '█', name: 'Full Block' },
      { char: '▓', name: 'Dark Shade' },
      { char: '▒', name: 'Medium Shade' },
      { char: '░', name: 'Light Shade' },
      { char: '▪', name: 'Black Small Square' },
      { char: '▫', name: 'White Small Square' },
      { char: '●', name: 'Black Circle' },
      { char: '○', name: 'White Circle' },
      { char: '◆', name: 'Black Diamond' },
      { char: '◇', name: 'White Diamond' },
      { char: '◼', name: 'Black Medium Square' },
      { char: '◻', name: 'White Medium Square' },
    ],
  },
];

/** Every character in the map, flattened, in group order. */
export const allCharacters: MapCharacter[] = characterGroups.flatMap(g => g.characters);

/** The code point of a character, as U+XXXX. Astral characters are handled by codePointAt. */
export function codePoint(char: string): string {
  const cp = char.codePointAt(0) ?? 0;
  return `U+${cp.toString(16).toUpperCase().padStart(4, '0')}`;
}

/** The HTML entity to paste into markup: the named one when it exists, the numeric one otherwise. */
export function htmlEntity(c: MapCharacter): string {
  if (c.entity) return `&${c.entity};`;
  const cp = c.char.codePointAt(0) ?? 0;
  return `&#${cp};`;
}

/** The CSS content escape: a backslash, the hex code point, and a trailing space to end it. */
export function cssEscape(char: string): string {
  const cp = char.codePointAt(0) ?? 0;
  return `\\${cp.toString(16).toUpperCase()}`;
}

/** The JavaScript string escape, in the \u{...} form that covers every code point. */
export function jsEscape(char: string): string {
  const cp = char.codePointAt(0) ?? 0;
  return cp > 0xffff
    ? `\\u{${cp.toString(16).toUpperCase()}}`
    : `\\u${cp.toString(16).toUpperCase().padStart(4, '0')}`;
}
