// Site identity: the one place the site's name, origin and accounts live.
//
// Everything that used to be a string literal scattered across layouts, endpoints and helpers
// (the production origin, the brand name, the title suffix, the X account, the GA measurement id,
// the production hostnames) is declared here once and imported everywhere else. There is still
// exactly one site; this module is the seam a second one would plug into later, not a
// multi-domain config.
//
// Each value is its own named export so a client bundle that needs one of them (the analytics
// guard reads the hostnames and the GA id) tree-shakes the rest away. `SITE` groups them for
// build-time readers that want the whole identity in one import.

/**
 * The production origin, no trailing slash. It is the fallback wherever `Astro.site` (the
 * `ASTRO_SITE` env var, see astro.config.mjs) is not set, and the pinned origin of the JSON-LD
 * `@id`s in src/lib/schema/identity.ts, which stay production values in every build.
 */
export const SITE_ORIGIN = 'https://toytoolsapp.com';

/**
 * Hostnames that count as production. Google Analytics loads and the service worker registers on
 * these (in the top window) and nowhere else, so a preview deploy, a mirror, a copy of the build
 * on another host or a framed page never reports and never installs a worker.
 */
export const PRODUCTION_HOSTNAMES: readonly string[] = ['toytoolsapp.com', 'www.toytoolsapp.com'];

/** The brand as it is written in titles, JSON-LD names and the X card. */
export const BRAND_NAME = 'ToyTools';

/** Appended to every browser title by src/lib/titles.ts. */
export const TITLE_SUFFIX = ` ● ${BRAND_NAME}`;

/** The site's own X account, signed next to "Powered by ToyTools" and in `twitter:site`. */
export const BRAND_X_HANDLE = '@ToytoolsApp';
export const BRAND_X_URL = 'https://x.com/ToytoolsApp';

/** The one GA4 property. Loaded only where src/lib/analytics/guard.ts allows it. */
export const GA_MEASUREMENT_ID = 'G-WHD7CL44MX';

/**
 * The social card every page shares as og:image and twitter:image: a 1200x630 PNG in public/,
 * generated by `npm run brand:generate`. A root-relative path; BaseLayout makes it absolute.
 */
export const SOCIAL_IMAGE_PATH = '/og.png';

/**
 * The site URL to resolve absolute links against: `Astro.site` when the build sets one, the
 * production origin otherwise. Returns a URL with a trailing-slash path, like `Astro.site`.
 */
export function siteUrl(site?: URL | string | null): URL {
  return new URL(site ?? `${SITE_ORIGIN}/`);
}

export const SITE = {
  origin: SITE_ORIGIN,
  productionHostnames: PRODUCTION_HOSTNAMES,
  brandName: BRAND_NAME,
  titleSuffix: TITLE_SUFFIX,
  x: { handle: BRAND_X_HANDLE, url: BRAND_X_URL },
  gaMeasurementId: GA_MEASUREMENT_ID,
  socialImagePath: SOCIAL_IMAGE_PATH,
} as const;
