// FROZEN. Tools that shipped before 2026-09-29 without a specific `citation.nonGoal`.
//
// llms-full.txt prints one "Does not:" line per tool. A tool with no nonGoal prints the generic
// "Does not: Call an AI model.", which is true of every tool on the site and so tells an assistant
// nothing about THIS one. On 2026-09-29, 149 of 166 tools printed it.
//
// The rule (CLAUDE.md, "LLM files"): every NEW tool sets a specific nonGoal in the same PR that adds
// it. This list is the backlog that rule does not reach, and it is a ratchet:
//   - it only ever SHRINKS. Never add a slug here; give the new tool a nonGoal instead.
//   - a tool on this list that gains a specific nonGoal must be removed from it in the same PR
//     (validate-registry fails until it is), so the list stays an exact picture of the backlog.
//   - a slug that leaves the registry (removed or renamed) must be removed from it too. A renamed
//     tool counts as new, so it needs its own nonGoal.
// Backfilling this list is deliberate follow-up work, not part of C1 (beta-v12.1.1).
//
// Enforced by nonGoalRatchetErrors() in ./nongoal.ts, called from scripts/validate-registry.ts.

export const NON_GOAL_BACKLOG: readonly string[] = Object.freeze([
  // Authored tools (src/tools/<segment>/<slug>/config.ts), 128.
  'age-calculator',
  'aspect-ratio-calculator',
  'base64-encoder-decoder',
  'binary-converter',
  'binary-text-converter',
  'bmi-calculator',
  'bmr-calculator',
  'body-fat-calculator',
  'body-weight-tracker',
  'book-tracker',
  'breathing-circle',
  'cagr-calculator',
  'calorie-deficit-calculator',
  'camel-case-converter',
  'character-map',
  'cidr-calculator',
  'coin-flipper',
  'color-contrast-checker',
  'color-format-converter',
  'combinations-permutations-calculator',
  'compound-interest-calculator',
  'crc32-hash-generator',
  'cron-expression-parser',
  'csv-cleaner',
  'csv-diff',
  'csv-to-json-converter',
  'csv-to-tsv',
  'date-difference-calculator',
  'dice-roller',
  'discount-calculator',
  'emergency-fund-calculator',
  'encoding-detector',
  'equalizer-settings-generator',
  'find-replace',
  'fraction-calculator',
  'gears',
  'habit-streak-tracker',
  'hash-identifier',
  'heart-rate-zone-calculator',
  'hex-encoder-decoder',
  'html-entity-encoder-decoder',
  'ideal-weight-calculator',
  'inflation-calculator',
  'invisible-character-detector',
  'json-diff',
  'json-escape',
  'json-minifier',
  'json-to-csv-converter',
  'json-to-yaml-converter',
  'json-tree-viewer',
  'json-validator',
  'kebab-case-converter',
  'keep-screen-awake',
  'kinetic-sand',
  'letter-counter',
  'line-counter',
  'lorem-ipsum-generator',
  'lowercase-converter',
  'macro-calculator',
  'margin-calculator',
  'markup-calculator',
  'move-today-tracker',
  'normalize-whitespace',
  'notepad',
  'number-to-words',
  'one-rep-max-calculator',
  'paragraph-counter',
  'percentage-calculator',
  'pomodoro-timer',
  'pop-it',
  'prime-factorization-calculator',
  'protein-intake-calculator',
  'punycode-converter',
  'px-to-dp-converter',
  'px-to-rem-converter',
  'qr-code-generator',
  'random-choice-picker',
  'random-name-picker',
  'random-string-generator',
  'reading-time-calculator',
  'regex-tester',
  'remove-accents',
  'remove-blank-lines',
  'remove-duplicate-lines',
  'remove-emoji',
  'remove-extra-spaces',
  'remove-line-breaks',
  'remove-tabs',
  'reverse-text',
  'roi-calculator',
  'roman-numeral-converter',
  'rot13-encoder-decoder',
  'rule-of-72-calculator',
  'running-pace-calculator',
  'savings-goal-calculator',
  'scientific-calculator',
  'sentence-case-converter',
  'shell-quote-escalator',
  'shop-upi-tally',
  'sip-calculator',
  'slime',
  'slugify-text',
  'snake-case-converter',
  'space-counter',
  'spinner',
  'split-bill',
  'statistics-visualizer',
  'switch-board',
  'systemd-timer-converter',
  'tax-calculator',
  'tdee-calculator',
  'text-compare',
  'text-repeater',
  'timezone-converter',
  'tip-calculator',
  'title-case-converter',
  'todo-list',
  'trim-text',
  'unix-timestamp-converter',
  'upi-mdr-estimator',
  'uppercase-converter',
  'url-encoder-decoder',
  'uuid-generator',
  'uuid-inspector',
  'water-intake-tracker',
  'what-is-my-ip',
  'word-frequency-counter',
  'yaml-to-json-converter',
  // Simulations (src/lib/simulation/simulations/*.manifest.ts), 21.
  'chemical-bond-calculator',
  'crystal-field-splitting-calculator',
  'doppler-effect-calculator',
  'electron-configuration-calculator',
  'frequency-period-calculator',
  'heat-transfer-calculator',
  'ideal-gas-law-calculator',
  'inclined-plane-calculator',
  'molecular-geometry-calculator',
  'momentum-collision-calculator',
  'newman-projection-calculator',
  'nuclear-reactor-calculator',
  'ohms-law-calculator',
  'pendulum-period-calculator',
  'probability-calculator',
  'projectile-motion-calculator',
  'quadratic-equation-solver',
  'reaction-rate-calculator',
  'simple-harmonic-motion-calculator',
  'unit-circle-calculator',
  'wave-speed-calculator',
]);
