// Committed code map — the one-file answer to "where does X live?".
//
// Serializes the live TS registries into docs/code-map.json: every tool's slug → directory,
// engine/pattern/family, processorId, group membership, which files exist on disk, and which
// content surfaces (guide/faq/knowledge) are registered — plus the engine and group manifests.
// Agents and tooling read this single JSON instead of grepping the registries, and the
// hand-maintained directory tree that used to live in CLAUDE.md is retired in its favor.
//
// The map is deterministic (no timestamps) so it diffs cleanly. validate-architecture.ts
// rebuilds it in memory on every `npm run build` and fails on drift, so it can never rot.
// Regenerate with `npm run map:generate` (scaffold-tool runs it automatically).

import { existsSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { tools } from '../src/data/registry';
import { categories } from '../src/data/categories';
import { engineRegistry } from '../src/data/engines';
import { toolGroups } from '../src/data/tool-groups';
import { registeredGuideSlugSet } from '../src/data/guide-registry';
import { faqsByToolSlug } from '../src/data/faq-registry';
import { KNOWLEDGE } from '../src/lib/knowledge/registry';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
export const CODE_MAP_PATH = join(repoRoot, 'docs', 'code-map.json');

export function buildCodeMap() {
  const segmentByCategory = new Map(categories.map(c => [c.slug, c.segment]));

  return {
    $schema: 'ToyTools code map — generated by scripts/export-code-map.ts; do not edit by hand',
    engines: Object.fromEntries(
      engineRegistry.map(e => [
        e.id,
        {
          name: e.name,
          category: e.category,
          patterns: e.patterns,
          runtimeGlobal: e.runtimeGlobal,
          sharedWidget: e.sharedWidget ? `src/tools/_shared/${e.sharedWidget}` : '',
          supportedFamilies: e.supportedFamilies,
          toolCount: e.toolCount,
        },
      ]),
    ),
    toolGroups: Object.fromEntries(
      toolGroups.map(g => [g.id, { name: g.name, members: g.members.map(m => m.slug) }]),
    ),
    tools: Object.fromEntries(
      tools.map(tool => {
        const segment = segmentByCategory.get(tool.categorySlug) ?? tool.categorySlug;
        const dir = `src/tools/${segment}/${tool.slug}`;
        const absDir = join(repoRoot, dir);
        const files = existsSync(absDir) ? readdirSync(absDir).sort() : [];
        return [
          tool.slug,
          {
            name: tool.name,
            dir,
            categorySlug: tool.categorySlug,
            url: `/tool/${segment}/${tool.slug}/`,
            engine: tool.engine ?? '',
            pattern: tool.pattern ?? '',
            family: tool.family ?? '',
            processorId: tool.processorId ?? '',
            toolGroup: tool.toolGroup ?? '',
            files,
            guideRegistered: registeredGuideSlugSet.has(tool.slug),
            faqRegistered: (faqsByToolSlug[tool.slug]?.length ?? 0) > 0,
            knowledgeRegistered: KNOWLEDGE.has(tool.slug),
          },
        ];
      }),
    ),
  };
}

export function serializeCodeMap(): string {
  return JSON.stringify(buildCodeMap(), null, 2) + '\n';
}

export function writeCodeMap(): void {
  writeFileSync(CODE_MAP_PATH, serializeCodeMap());
}

// Write only when executed directly (`npm run map:generate`), not when imported
// by validate-architecture for the freshness diff.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  writeCodeMap();
  console.log(`[export-code-map] wrote ${tools.length} tools → docs/code-map.json`);
}
