// The X content pipeline: derive drafts from the registry, gate them on the site's own voice
// rules, and write a reviewable queue.
//
//   npm run x:generate -- --slug base64-encoder-decoder --print   validated draft to stdout, no
//                                                                 files touched. This is how the
//                                                                 x-content skill pulls sourced
//                                                                 material for a conversational
//                                                                 suggestion (see SKILL.md) --
//                                                                 the default way this gets used.
//   npm run x:generate               all kinds, writes the full brand/social/x/queue/ bulk export
//   npm run x:generate -- --kind gotcha --limit 10
//   npm run x:generate -- --check    validate only, non-zero exit on a failure. For CI.
//
// Why a generator rather than a document listing post ideas: the same reason brand/ holds a
// generator rather than an exported design file. A list of 75 post ideas written by hand goes
// stale the first time a tool's craft sentence is rewritten, and nothing fails when it does.
// Deriving from the registry means a draft that no longer matches the site cannot survive a run --
// which is exactly the guarantee `--print` exists to give a one-off conversational suggestion
// without writing 218 files to get it.
//
// The bulk export (no flags) writes one file per draft, not one file per kind: 131 threads in a
// single thread.md meant scrolling past 130 topics to post one. Each draft gets its own file at
// brand/social/x/queue/<kind>/<slug>.md, named for the tool or topic it's about, with its post text
// in a fenced code block so a copy grabs exactly what gets pasted, no blockquote markers included.
// queue/index.md is the one place that still lists everything. This is the occasional "I want to
// browse everything at once" path, not the default one.
//
// What this does NOT do: post anything. There is no X API credential in this repo and no
// intention to add one. Publishing stays a human action, which is also what keeps the demand
// probes honest -- an account that auto-posts cannot notice what it is measuring.

import { mkdirSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import path from 'node:path';
import { buildDrafts, knownUrls } from './x-content/build-drafts';
import { validate, postLength, X_LIMIT } from './x-content/validate';
import type { Draft, DraftKind } from './x-content/types';

const OUT = path.resolve(process.cwd(), 'brand/social/x/queue');
const CARDS_DIR = 'brand/social/x/cards';

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i === -1 ? undefined : process.argv[i + 1];
}
const has = (name: string) => process.argv.includes(`--${name}`);

/** The id is `<kind>-<rest>`; the file only needs the meaningful part, since the kind is already the directory. */
function slugFor(draft: Draft): string {
  return draft.id.slice(draft.kind.length + 1).replace(/[^a-z0-9.-]/gi, '-');
}

function relPath(draft: Draft): string {
  return `${draft.kind}/${slugFor(draft)}.md`;
}

/**
 * Text-only is the default; a card is a rare, deliberate exception, never a paired asset every
 * post gets. This line makes that policy visible per draft, and points at the real image path
 * once one exists rather than just the command that would produce it.
 */
function imageLine(draft: Draft): string {
  if (!draft.card) return '- **image** none (text-only)\n';
  const stillSlotted = /\[\[/.test(draft.card.body) || /\[\[/.test(draft.card.headline);
  if (!stillSlotted) {
    return `- **image** \`${CARDS_DIR}/${draft.id}.png\` (npm run x:cards -- --id ${draft.id} to (re)render it)\n`;
  }
  return (
    `- **image** none by default. Optional \`${draft.card.template}\` card: fill the short phrase ` +
    `in the card slot ONLY if this post earns extra reach, then \`npm run x:cards -- --id ${draft.id}\`. ` +
    `Keep it minimal, a phrase, not a paragraph.\n`
  );
}

function render(draft: Draft): string {
  const head =
    `# ${draft.subject}\n\n` +
    `- **kind** \`${draft.kind}\`\n` +
    `- **why** ${draft.rationale}\n` +
    (draft.landing ? `- **lands on** ${draft.landing}\n` : `- **lands on** nothing, on purpose\n`) +
    imageLine(draft) +
    `\n` +
    `Generated by \`npm run x:generate\`. Do not edit here: edit the registry field a draft quotes, ` +
    `or the draft template in \`scripts/x-content/build-drafts.ts\`, and re-run. A \`[[slot]]\` is ` +
    `prose the generator cannot write; see \`.claude/skills/x-content/\`.\n`;

  const body = draft.posts
    .map((p) => {
      const n = draft.posts.length > 1 ? `## ${p.index}/${draft.posts.length}` : '## post';
      const len = postLength(p.text);
      const slots = (p.text.match(/\[\[/g) ?? []).length;
      const meta = `\`${len}/${X_LIMIT} chars\`${slots ? ` \`${slots} slot${slots > 1 ? 's' : ''} to fill\`` : ''}`;
      // A fenced block, not a blockquote: selecting and copying it grabs exactly the text that
      // gets pasted into X, with no `>` markers or reflowed line breaks to strip out by hand.
      return `${n} ${meta}\n\n\`\`\`text\n${p.text}\n\`\`\`\n\n<sub>${p.sources.join(' · ')}</sub>`;
    })
    .join('\n\n');

  return `${head}\n---\n\n${body}\n`;
}

function writeIndex(drafts: Draft[], failedCount: number): void {
  const byKind = new Map<DraftKind, Draft[]>();
  for (const d of drafts) byKind.set(d.kind, [...(byKind.get(d.kind) ?? []), d]);

  const kindOrder: DraftKind[] = ['thread', 'gotcha', 'probe', 'ship'];
  const sections = kindOrder
    .filter((k) => byKind.has(k))
    .map((k) => {
      const list = byKind.get(k)!;
      const rows = list
        .map((d) => {
          const image = !d.card
            ? 'none'
            : /\[\[/.test(d.card.body) || /\[\[/.test(d.card.headline)
              ? 'optional'
              : 'ready';
          return `| [${d.subject}](${relPath(d)}) | ${d.posts.length} | ${image} |`;
        })
        .join('\n');
      return `## ${k} (${list.length})\n\n| topic | posts | image |\n|---|---|---|\n${rows}`;
    });

  writeFileSync(
    path.join(OUT, 'index.md'),
    `# X content queue\n\n` +
      `Generated by \`npm run x:generate\`. One file per draft, under \`<kind>/<slug>.md\` -- open the ` +
      `one you're about to post rather than scrolling this list. **image** is \`none\` (text-only, the ` +
      `default), \`optional\` (a card exists but its slot isn't filled, so nothing renders yet), or ` +
      `\`ready\` (the card has real text; \`npm run x:cards\` will render it).\n\n---\n\n` +
      sections.join('\n\n---\n\n') +
      '\n',
  );
}

function main() {
  const all = buildDrafts();
  const kind = arg('kind') as DraftKind | undefined;
  const slug = arg('slug');
  const limit = Number(arg('limit') ?? 0);

  let drafts = all;
  if (kind) drafts = drafts.filter((d) => d.kind === kind);
  if (slug) drafts = drafts.filter((d) => d.id.includes(slug));

  const issues = validate(drafts, knownUrls());

  if (issues.length) {
    console.error(`\n[x-content] ${issues.length} draft(s) failed the voice gate:\n`);
    for (const i of issues) console.error(`  ${i.draftId} #${i.postIndex}  ${i.rule}: ${i.detail}`);
    console.error('');
  }

  if (has('check')) {
    if (issues.length) process.exit(1);
    console.log(`[x-content] ${drafts.length} drafts pass the voice gate`);
    return;
  }

  // Prints validated draft(s) to stdout and touches no files -- not the queue, not its index. The
  // narrow, non-destructive way to pull one sourced draft for a conversational suggestion, so
  // reaching for a single idea never wipes whatever bulk export already exists on disk.
  if (has('print')) {
    if (issues.length) process.exit(1);
    if (!drafts.length) {
      console.error('[x-content] no draft matches that --kind/--slug.');
      process.exit(1);
    }
    console.log(drafts.map(render).join('\n---\n\n'));
    return;
  }

  // A failing draft is never written to the queue. The queue is the thing a person posts from,
  // so anything in it has already cleared the same bar the site's prose clears.
  const failed = new Set(issues.map((i) => i.draftId));
  const clean = drafts.filter((d) => !failed.has(d.id));

  if (existsSync(OUT)) rmSync(OUT, { recursive: true });
  mkdirSync(OUT, { recursive: true });

  const byKind = new Map<DraftKind, Draft[]>();
  for (const d of clean) byKind.set(d.kind, [...(byKind.get(d.kind) ?? []), d]);

  const counts: string[] = [];
  for (const [k, list] of byKind) {
    const capped = limit ? list.slice(0, limit) : list;
    mkdirSync(path.join(OUT, k), { recursive: true });
    for (const draft of capped) {
      writeFileSync(path.join(OUT, relPath(draft)), render(draft));
    }
    counts.push(`${capped.length} ${k}`);
  }

  const written = [...byKind.values()].flatMap((list) => (limit ? list.slice(0, limit) : list));
  writeIndex(written, failed.size);
  writeFileSync(path.join(OUT, 'queue.json'), JSON.stringify(written, null, 2));

  console.log(`[x-content] wrote brand/social/x/queue/ -- ${counts.join(', ')} (see index.md)`);
  if (failed.size) console.log(`[x-content] ${failed.size} draft(s) held back by the voice gate`);
}

main();
