// The X content pipeline: derive drafts from the registry, gate them on the site's own voice
// rules, and write a reviewable queue.
//
//   npm run x:generate               all kinds, writes brand/social/x/queue/
//   npm run x:generate -- --kind gotcha --limit 10
//   npm run x:generate -- --slug base64-encoder-decoder
//   npm run x:generate -- --check    validate only, non-zero exit on a failure. For CI.
//
// Why a generator rather than a document listing post ideas: the same reason brand/ holds a
// generator rather than an exported design file. A list of 75 post ideas written by hand goes
// stale the first time a tool's craft sentence is rewritten, and nothing fails when it does.
// Here the queue is regenerated from the registry, so a draft that no longer matches the site
// cannot survive a run.
//
// What this does NOT do: post anything. There is no X API credential in this repo and no
// intention to add one. Publishing stays a human action, which is also what keeps the demand
// probes honest -- an account that auto-posts cannot notice what it is measuring.

import { mkdirSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import path from 'node:path';
import { buildDrafts, knownUrls } from './x-content/build-drafts';
import { validate, postLength, X_LIMIT } from './x-content/validate';
import type { Draft, DraftKind } from './x-content/types';

const OUT = path.resolve(process.cwd(), 'brand/social/x/queue');

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i === -1 ? undefined : process.argv[i + 1];
}
const has = (name: string) => process.argv.includes(`--${name}`);

function render(draft: Draft): string {
  const head =
    `## ${draft.subject}\n\n` +
    `- **kind** \`${draft.kind}\`\n` +
    `- **why** ${draft.rationale}\n` +
    (draft.landing ? `- **lands on** ${draft.landing}\n` : `- **lands on** nothing, on purpose\n`) +
    (draft.card ? `- **card** \`${draft.card.template}\` (npm run x:cards -- --id ${draft.id})\n` : '');

  const body = draft.posts
    .map((p) => {
      const n = draft.posts.length > 1 ? `### ${p.index}/${draft.posts.length}` : '### post';
      const len = postLength(p.text);
      const slots = (p.text.match(/\[\[/g) ?? []).length;
      const meta = `\`${len}/${X_LIMIT} chars\`${slots ? ` \`${slots} slot${slots > 1 ? 's' : ''} to fill\`` : ''}`;
      return `${n} ${meta}\n\n${p.text.split('\n').map((l) => (l ? `> ${l}` : '>')).join('\n')}\n\n<sub>${p.sources.join(' · ')}</sub>`;
    })
    .join('\n\n');

  return `${head}\n${body}\n`;
}

function main() {
  const all = buildDrafts();
  const kind = arg('kind') as DraftKind | undefined;
  const slug = arg('slug');
  const limit = Number(arg('limit') ?? 0);

  let drafts = all;
  if (kind) drafts = drafts.filter((d) => d.kind === kind);
  if (slug) drafts = drafts.filter((d) => d.id.includes(slug));

  const issues = validate(drafts, knownUrls());

  if (issues.length) {
    console.error(`\n[x-content] ${issues.length} draft(s) failed the voice gate:\n`);
    for (const i of issues) console.error(`  ${i.draftId} #${i.postIndex}  ${i.rule}: ${i.detail}`);
    console.error('');
  }

  if (has('check')) {
    if (issues.length) process.exit(1);
    console.log(`[x-content] ${drafts.length} drafts pass the voice gate`);
    return;
  }

  // A failing draft is never written to the queue. The queue is the thing a person posts from,
  // so anything in it has already cleared the same bar the site's prose clears.
  const failed = new Set(issues.map((i) => i.draftId));
  const clean = drafts.filter((d) => !failed.has(d.id));
  const byKind = new Map<DraftKind, Draft[]>();
  for (const d of clean) byKind.set(d.kind, [...(byKind.get(d.kind) ?? []), d]);

  if (existsSync(OUT)) rmSync(OUT, { recursive: true });
  mkdirSync(OUT, { recursive: true });

  const counts: string[] = [];
  for (const [k, list] of byKind) {
    const capped = limit ? list.slice(0, limit) : list;
    const file = path.join(OUT, `${k}.md`);
    writeFileSync(
      file,
      `# ${k} drafts\n\n` +
        `Generated by \`npm run x:generate\`. Do not edit here: edit the registry field a draft ` +
        `quotes, or the draft template in \`scripts/x-content/build-drafts.ts\`, and re-run.\n\n` +
        `Every \`[[slot]]\` is prose the generator cannot write. See \`.claude/skills/x-content/\`.\n\n---\n\n` +
        capped.map(render).join('\n---\n\n'),
    );
    counts.push(`${capped.length} ${k}`);
  }

  writeFileSync(path.join(OUT, 'queue.json'), JSON.stringify(clean, null, 2));

  console.log(`[x-content] wrote brand/social/x/queue/ -- ${counts.join(', ')}`);
  if (failed.size) console.log(`[x-content] ${failed.size} draft(s) held back by the voice gate`);
}

main();
